### ISSUE TITLE
Fix SonarCloud GitHub Actions workflow

### ISSUE THREAD

**Issue by nrz** [nrz/ylikuutio#188]
Fix SonarCloud GitHub Actions workflow.

Commit b3565e05d08a3cf8cde680850e70140cbcf64f9b fixed SonarCloud analysis build, but at the moment executing SonarCloud still fails.

Some probably relevant information from the failing run: 

```
INFO: SonarScanner 4.7.0.2747
INFO: Java 11.0.14.1 Eclipse Adoptium (64-bit)
INFO: Linux 6.5.0-1017-azure amd64
```
...

```
ERROR: Error during SonarScanner execution
java.lang.IllegalStateException: The plugin [python] does not support Java 11.0.14.1
	at org.sonar.core.platform.PluginLoader.instantiatePluginClasses(PluginLoader.java:123)
	at org.sonar.core.platform.PluginLoader.load(PluginLoader.java:54)
	at org.sonar.scanner.bootstrap.ScannerPluginRepository.start(ScannerPluginRepository.java:62)
```
... stack trace continues ...
```
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.lang.UnsupportedClassVersionError: org/sonar/plugins/python/PythonPlugin has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```

**Comment by nrz** [comment]
Completed.
